<div id="content">
                	<div class="maincontent-inner">
                    
                        <div class="invite-area">
					 
					 
					 <div id="contactFormArea">                                
                                    <!-- Contact Form Start //-->
                                    <form name="invite" id="invite" method="post" >
                                    <fieldset>
                                    
                                    <div class="label-form-inline">
                                    <label>
                                    <h4>Name</h4>
                                    </label>
                                    <input type="text" name="name" id="name" class="event-textfield" />
                                    </div>
                                    <div class="label-form-inline">
                                    <label>
                                    <h4>Email</h4>
                                    </label>
                                    <input type="text" name="email" id="email"  class="event-textfield" />
                                    </div>
									<div class="label-form-inline">
                                    <label>
                                    <h4>Message</h4>
                                    </label>
                                    <textarea name="message" id="message"  class="event-textarea" cols="2" rows="7"></textarea>
                                    </div>
                                    </fieldset> 
									<div class="label-form-inline"><input type="submit" name="submit" class="buttoncontact" id="buttonsend" value="Cancel" /> <input type="submit" name="submit_invite" id="submit_invite" class="buttoncontact" value="Save" />
                                    <span class="loading" style="display: none;">Please wait..</span></div>
                                    </form>
                                    <!-- Contact Form End //-->                                      
                                </div>
					 
					 
					 
					 </div>
                        
                        
                       
                </div>
                <!-- END OF CONTENT -->                              
                        
                            
                
                
                    
                </div>   