<div id="nav_panel">
<div id="nav_bar">
	<ul class="sf-menu">
			<li class="current">
				<a href="/admin/index/dashboard">Home</a>				
			</li>
            <li>
				<a href="#" onclick="showEventCategoriesListing()">Event Categories</a>
			</li>
			<li>
				<a href="#" onclick="showEventsListing()">Events</a>
			</li>
            <li>
				<a href="#" onclick="showMembershipPlansListing()">Membership Plans</a>
			</li>
            <li>
				<a href="#" onclick="showCoordinatorsListing()">Co-Ordinators</a>
                <ul>
					<li>
						<a href="#" onclick="showSubCoordinatorsListing(0)">Sub Co-Ordinator</a>						
					</li>					
				</ul>
			</li>
            <li>
				<a href="#" onclick="showMembersListing()">Members</a>
			</li>
            <li>
				<a href="#" onclick="showEmailTemplatesListing()">Email Templates</a>
			</li>
            <li>
				<a href="#" onclick="showAdministratorsListing()">Administrator</a>
                <ul>
					<li>
						<a href="#" onclick="showAdministratorsGroupsListing()">Administrator Goups</a>						
					</li>					
				</ul>
			</li>
			<li>
				<a href="#">Reports</a>
				<ul>
					<li>
						<a href="#" onclick="ShowMembersReport()">Members Report</a>						
					</li>
					<li>
						<a href="#" onclick="ShowCoOrdinatorsReport()">Co Ordinators Report</a>						
					</li>
					<li>
						<a href="#" onclick="ShowEventsReport()">Events Report</a>						
					</li>
					<li>
						<a href="#" onclick="ShowTicketsReport()">Tickets Report</a>						
					</li>
					<li>
						<a href="#" onclick="ShowTransactionsReport()">Transactions Report</a>						
					</li>
				</ul>
			</li>
            <li>
				<a href="#" onclick="showBillingsListing()">Billing</a>                
                <ul>
					<li>
						<a href="#" onclick="showBillingTransactionsListing(0)">Transactions</a>						
					</li>
					<li>
						<a href="#" onclick="showBillingInvoicesListing(0)">Invoices</a>						
					</li>
					<li>
						<a href="#" onclick="showBillingMembershipsListing(0)">Memberships</a>						
					</li>					
				</ul>                
			</li>
            <li>
				<a href="#" onclick="showThemesListing()">Themes</a>                
			</li>			
		</ul>

</div>
<div id="loginbt"><img src="images/login_bt.jpg" /></div>

</div>