<div id="content">
	<div class="maincontent">    
    <div class="myeventbg"> 
    <div class="animatedtabs">
      <ul>
        <li><a href="/createevent" title="Create Event"><span>Create Event</span></a></li>
        <li><a href="/myevents"    title="My Events"><span>My Events</span></a></li>
        <li><a href="/mytickets"   title="My Purchased Tickets"><span>My Purchased Tickets</span></a></li>
        <li><a href="/deletedevents"   title="My Deleted Events"><span>My Deleted Events</span></a></li>
        <li><a href="/myprofile"   title="My Profile"><span>My Profile</span></a></li>
        <li><a href="/account"     title="My Account"><span>My Account</span></a></li>
        <li style="margin-left: 110px;"><a href="javascript:history.go(-1);" title="Go Back" ><span>Go Back</span></a></li>
      </ul>
    </div>   
    </div>
    <?php if(!empty($this->result)){?>
    <div id="eventLongBar">
    <div id="eventName">Event</div>
    <div id="eventDate">Event Date</div>
    <div id="eventStatus">Total Tickets</div>    
    <div id="eventActions">Actions</div>
    <div style="clear:both;"></div>
    <?php 
    foreach($this->result as $key=>$value)
    {
    ?>    
    <div class="eventbar" id="myevent<?php echo $value['id']; ?>" onmouseover="ShowMyEventHoverBar(<?php echo $value['id']; ?>)" onmouseout="HideMyEventHoverBar(<?php echo $value['id']; ?>)" >
    <div class="eventUnderName"><?php echo $value['title']; ?></div>
    <div class="eventUnderDate"><?php echo $value['start_date']; ?></div>
    <div class="eventUnderStatus"><?php echo $value['total_quantity']; ?></div>         
    <div style="display: none;" id="action<?php echo $value['id']; ?>" class="eventUnderActions">
      <div>
        <div id="print_tickets">
          <p><a title="Print Tickets" href="/orderstart/printticket?oid=<?php echo $value['oid']; ?>" id="print_tickets" class="press-it-btn"></a></p>
        </div>
      </div>
    </div> 
    
    </div> 
    <div style="clear:both;"></div>
    <?php     
    }
    ?>
    </div>
    <?php }else{?>
    <div style="text-align: center;">There are no records</div>
    <?php } ?>
        
    
	</div>
</div>