<div id="content">
    <div class="maincontent-inner">
    <div class="contact-area"> 
    <h4>Forgot Password</h4>                                                                
    <div id="contactFormArea">                                
        <!-- Contact Form Start //-->
        <form name="forgotpassword" id="forgotpassword" method="post" >
        <fieldset>
        <div class="label-form-inline">
        <label>Email</label>
        <input type="text" name="user_email"  id="user_email"  size="25" class="textfield field-nomargin" />
        </div>        
        <button type="submit" name="submit_forgotpassword" id="submit_forgotpassword" class="button-login" >Submit</button>
        <span class="loading" style="display: none;">Please wait..</span>
        </fieldset> 
        </form>
        <!-- Contact Form End //-->                                      
    </div>      
    </div> 
    </div>
</div>   