<div id="content">
    <div class="maincontent-inner">        
    <div class="contact-area"> 
    <h4>SignUp</h4>                                                                
    <div id="contactFormArea">                                
        <!-- Contact Form Start //-->
        <form name="signup" id="signup" method="post" >
        <fieldset>
        <div class="label-form-inline">
        <label>Membership Package</label>
        <select name="membership_id" id="membership_id" class="textfield">        
        <option value="1">Basic Membership</option>
        </select>        
        </div>
        
        <div class="label-form-inline">
        <label>First Name</label>
        <input type="text" name="user_first_name" id="user_first_name" size="25"  class="textfield" />
        </div>
        <div class="label-form-inline">
        <label>Last Name</label>
        <input type="text" name="user_last_name"  id="user_last_name"  size="25" class="textfield" />
        </div>
        <div class="label-form-inline">
        <label>Email</label>
        <input type="text" name="user_email"  id="user_email"  size="25" class="textfield field-nomargin" />
        </div>
        <div class="label-form-inline">
        <label>Password</label>
        <input type="password" name="user_password" id="user_password" size="25" class="textfield field-nomargin" />
        </div>                                   
        
        <button type="submit" name="submit_signup" id="submit_signup" class="button-login">Submit</button>
        <span class="loading" style="display: none;">Please wait..</span>
        </fieldset> 
        </form>
        <!-- Contact Form End //-->                                      
    </div>       
    </div> 
    </div>
</div>   
    