<div id="content"> 
  <div class="maincontent-inner">
<div id="error_event_quantity" style="display:none;">Invalid quantity.  Please enter a quantity of 1 or more.</div>
<div id="error_event_quantity_remaining" style="display:none;">There are not enough tickets to satisfy your request.</div>

<div id="error_event_name" style="display:none;">Please enter your name.</div>
<div id="error_event_email" style="display:none;">Please enter an email address.</div>
<div id="error_event_valid_email" style="display:none;">Please enter a valid email address.</div>
<div id="error_event_message" style="display:none;">Please enter your message or comments.</div>
<div id="error_event_code" style="display:none;">Please enter the code as shown on the image.</div>
<div id="error_event_date" style="display:none;">Please select the date you would like to attend.</div>
<div id="error_event_your_email" style="display:none;">Please enter an email address.</div>
<div id="error_event_valid_email_to" style="display:none;">Please enter a valid email address in the To: field.</div>
<div id="error_event_subject" style="display:none;">Please enter a subject for your message.</div>

<div id="error_event_message_email" style="display:none;">Please enter a message.</div>
<div id="error_event_invitation" style="display:none;">You can only send this invitations to 10 email addresses at a time.</div>
<div id="error_event_color" style="display:none;">$$$$ is not a properly formatted color.  Please use the format #RRGGBB for all colors.</div>
<div id="error_event_limit_message" style="display:none;">Please limit your message to $$$$ characters. There are currently ££££.</div>
<div id="error_event_invalid_email" style="display:none;">$$$$ is not a valid email address.</div>
<div id="error_event_discount" style="display:none;">Please enter a discount code.</div>
<div id="error_event_na" style="display:none;">N/A</div>
<div id="error_event_soldout" style="display:none;">Sold Out</div>

<div  id="error_register_exceeded" style="display:none;">You have exceeded the time limit and your reservation has been released.
	<br><br>The purpose of this time limit is to ensure that registration is available to as many people as possible.  We apologize for the inconvenience.</div>
<div id="error_register_optionnotavailable" style="display:none;">This is option is not available anymore.  Please choose a different option.</div>
<div id="error_register_waiver" style="display:none;">Please read and accept the waiver.</div>
<div id="error_register_required" style="display:none;">All fields marked with * are required.</div>
<div id="error_register_emailerror" style="display:none;">Please double check your email address.  The email address format does not appear valid.</div>
<div id="error_register_invalidnumber" style="display:none;">$$$$ requires a number between ££££ and §§§§</div>
<div id="error_register_invalidzipcode" style="display:none;">US Zipcodes need to be 5 digits.</div>
<div id="error_register_invalidurl" style="display:none;">Please double check your website URL.</div>

<div id="error_register_fieldrequired" style="display:none;">All fields marked with * are required.</div>
<div id="error_register_creditcardexpirationdate" style="display:none;">Your credit card expiration date is in the past.</div>
<div id="error_register_creditcardneed4digit" style="display:none;">Your credit card CSC needs to be 4 digits.</div>
<div id="error_register_paybycheck" style="display:none;">Please confirm your order:<br>$$$$<br>You have selected to Pay by Check.<br><br>Click OK to confirm your order.</div>
<div id="error_register_payatthedoor" style="display:none;">Please confirm your order:<br>$$$$<br>You have selected to Pay at the Door.<br><br>Click OK to confirm your order.</div>

<div id="error_register_payinvoice" style="display:none;">Please confirm your order: <br>$$$$<br>You have selected to Pay upon Receiving an Invoice.<br><br>Click OK to confirm your order.</div>
<div id="error_register_creditcardcsc" style="display:none;">Your credit card CSC needs to be 3 digits.</div>
<div id="error_register_billingzipcode" style="display:none;">Your billing zip code needs to be 5 digits.</div>
<div id="error_register_savingaddresserror" style="display:none;">There was a problem saving your address.</div>
<div id="error_register_savingcredtitcarderror" style="display:none;">There was a problem saving your credit card info.</div>
<div id="error_register_savinginfoerror" style="display:none;">There was a problem saving your personal information.</div>
<div id="error_register_selectadate" style="display:none;">Please select the date you would like to attend.</div>

<div id="error_register_mcafee" style="display:none;">McAfee Secure sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams.</div>
<div id="error_register_mcafeecopyright" style="display:none;">Copying Prohibited by Law - McAfee Secure is a Trademark of McAfee, Inc.</div>
<div id="error_register_creditcardunknown" style="display:none;">Unknown card type.</div>
<div id="error_register_creditcardmissingnumber" style="display:none;">No card number provided.</div>
<div id="error_register_creditcardinvalidnumber" style="display:none;">Credit card number is in invalid format.</div>
<div id="error_register_creditcardinvalidtype" style="display:none;">Wrong card type or credit card number is invalid.</div>
<div id="error_register_creditcardinvaliddigits" style="display:none;">Credit card number has an inappropriate number of digits.</div>
<div id="error_register_numeric" style="display:none;">Please enter numbers here.</div>
<div id="error_register_numericinteger" style="display:none;">Please enter an integer value.</div>

<div id="error_register_numericlength" style="display:none;">Numbers must be less or equal to $$$$</div>
<div id="error_register_requiredfieldsnotfilled" style="display:none;">All the required fields have not been filled out.  Click OK to proceed without all the required information, or click Cancel to finish entering the missing data.</div>

         
<div id="error_tickets_1" style="display:none;">Sorry, invalid event registration form.</div>
<div id="error_tickets_2" style="display:none;">Sorry, invalid event or database error.</div>
<div id="error_tickets_3" style="display:none;">Sorry, quantity must be a positive integer.</div>
<div id="error_tickets_4" style="display:none;">Sorry, you did not select a valid ticket.</div>
<div id="error_tickets_5" style="display:none;">Sorry, invalid event organizer email address.</div>
<div id="error_tickets_6" style="display:none;">Your order was canceled.</div>

<div id="error_tickets_7" style="display:none;">Thank You. Your order has been successfully completed. Your name and email address have been added to the list of event attendees.</div>
<div id="error_tickets_8" style="display:none;">Sorry, that option is sold out.</div>
<div id="error_tickets_9" style="display:none;">Sorry, that option is no longer available.</div>
<div id="error_tickets_10" style="display:none;">Sorry, there are only  tickets of that type still available.</div>
<div id="error_tickets_20" style="display:none;">Sorry, you entered an invalid quantity. Please enter a quantity of 1 or more next to the type or types of tickets you would like to purchase.</div>
<div id="error_tickets_21" style="display:none;">Sorry, you did not select any tickets to purchase. Please enter a quantity of 1 or more next to the type or types of tickets you would like to purchase.</div>
<div id="error_tickets_22" style="display:none;">
	Sorry, there are no tickets left for this event.</div>
<div id="error_tickets_23" style="display:none;">The tickets, ticket quantity or date and time you've requested are no longer available, due to previous sales. Please choose a different date, time or number of tickets and place your order again.</div>

<div id="error_tickets_24" style="display:none;">Sorry, one or more of the tickets you requested are no longer available for purchase.</div>
<div id="error_tickets_25" style="display:none;">Sorry, you need to select the date you want to attend.</div>
<div id="error_tickets_26" style="display:none;">Sorry, the discount code you entered is not valid yet.</div>
<div id="error_tickets_27" style="display:none;">Sorry, the discount code you entered has expired.</div>
<div id="error_tickets_28" style="display:none;">Sorry, the discount code you entered is not valid.</div>
<div id="error_tickets_29" style="display:none;">Your session has expired.  Try ordering again.</div>
<div id="error_tickets_30" style="display:none;">Sorry, the discount code you entered is not available any more.</div>
<div id="error_tickets_31" style="display:none;">Sorry, you need to enable javascript to place an order.<a href="http://help.eventbrite.com">How do I enable JavaScript on my computer?</a></div>

<div id="error_tickets_32" style="display:none;">Sorry, the tickets you are trying to order are not currently available.</div>
<div id="error_tickets_33" style="display:none;">Sorry, the payment type chosen is invalid for this event.</div>
<div id="error_tickets_34" style="display:none;">Sorry, there is only 1 ticket left for this event.</div>
<div id="error_tickets_35" style="display:none;">Sorry, there are only  tickets left for this event.</div>
<div id="error_tickets_36" style="display:none;">We're sorry, this invitation is invalid.</div>
<div id="error_tickets_37" style="display:none;">We're sorry, this invitation has already been used.</div>
<div id="error_tickets_38" style="display:none;">We're sorry, you already have an order being processed for this event. Please wait a few minutes and try again.</div>
<div id="error_tickets_39" style="display:none;">We're sorry, there is a problem with your invitation. Please try again.</div>
<div id="error_register_1" style="display:none;">Sorry, the payment type chosen is invalid for this event.</div>
<div id="error_register_2" style="display:none;">Sorry, your billing address was not saved properly, please try again.</div>
<div id="error_register_3" style="display:none;">Sorry, we experienced an internal error, please try again.</div>
<div id="error_register_4" style="display:none;">The captcha you entered is invalid. Please try again.</div>
<div id="error_register_5" style="display:none;">Invalid credit card selected. You have been logged out.</div>
<div id="error_waitlist_1" style="display:none;">Sorry, the payment type chosen is invalid for this event.</div>
<div id="error_waitlist_2" style="display:none;">Sorry, your billing address was not saved properly, please try again.</div>
<div id="error_waitlist_3" style="display:none;">Sorry, we experienced an internal error, please try again.</div>
<div id="data_event_state" style="display:none;">State</div>
<div id="data_event_zip" style="display:none;">Zip Code</div>
<div id="data_event_province" style="display:none;">Province</div>
<div id="data_event_postalcode" style="display:none;">Postal Code</div>
<div id="data_event_county" style="display:none;">County</div>
<div id="data_event_stateterritory" style="display:none;">State/Territory</div>

<div id="data_event_stateprovince" style="display:none;">State/Province</div>
    <?php if(basename($_SERVER['HTTP_REFERER']) == "createevent" || basename($_SERVER['HTTP_REFERER']) == "editevent"){ echo '<div style="float: left; width:800px;margin-bottom: 3px; text-align: center;" ><h1>Preview Mode</h1></div>'; }?>
    <div style="float: left; width:600px; margin:5px;">
    <?php if($this->eventdetail['logo']){?>      
      <div style="float: left;"><img src="/image?width=190&amp;height=60&amp;image=/event_logos/<?php echo $this->eventdetail['logo']; ?>" alt="<?php echo $this->eventdetail['title']; ?>" /></div>
    <? } ?>    
    <h3 style="float: left; margin-top: 15px; "><?php echo $this->eventdetail['title']; ?></h3></div>
    <?php if(basename($_SERVER['HTTP_REFERER']) == "createevent" || basename($_SERVER['HTTP_REFERER']) == "editevent"){ echo '<div style="float: left; width:300px; text-align: right;"><a href="/editevent?eid='.$this->eventdetail['id'].'">Edit Event &nbsp;<img src="/static/images/edit.png"></a></div>'; }?>    
    
    <div style="float:left; width:600px;">      
      <div class="event-area">
        <form name="mgform" id="mgform" onSubmit="return validateform();" action="/orderstart?ebtv=A" method="post">                   
            <fieldset>
            <div style="float: left; width:600px">
              <label>
              <h4>Ticket Details</h4>
              </label>
              <?php if(!empty($this->ticketdetail)){?>
              <table width="590" border="0" cellpadding="2" cellspacing="2">
                <tr>
                  <td width="180" align="left" class="text2"><strong>Ticket Type</strong></td>
                  <td width="120" align="center" class="text2"><strong>Sales Start</strong></td>
                  <td width="120"  align="center" class="text2"><strong>Sales End</strong></td>
                  <td width="50"  align="center" class="text2"><strong>Price</strong></td>
                  <td width="50"  align="right" class="text2"><strong>Quantity</strong></td>
                </tr>
                <?php foreach($this->ticketdetail as $key=>$value) { ?>
                <?php //echo $value['ticket_sold']; ?>
                <?php $total_ticket_quantity =  ($value['ticket_quantity']=="0")  ? '100000000000000000' : $value['ticket_quantity']; ?>
                <?php if(trim($value['ticket_start_sale_date']) != "0000-00-00" && trim($value['ticket_end_sale_date']) != "0000-00-00" ) {?>                                
                <tr class="ticket_row">
                  <td><strong><?=$value['ticket_title']?></strong></td>
                  <? //print_r($this->ticketdetail); ?>
                  <?php if( time() >  strtotime($value['ticket_start_sale_date']) &&    time() < strtotime($value['ticket_end_sale_date']) ) {?>
                  <td align="center"><?=($value['ticket_start_sale_date']=="0000-00-00 00:00:00" || $value['ticket_start_sale_date']=="0000-00-00") ? 'Event Publish Date' : date("F j, Y", strtotime($value['ticket_start_sale_date']));?></td>
                  <td align="center"><?=($value['ticket_end_sale_date']=="0000-00-00 00:00:00" || $value['ticket_end_sale_date']=="0000-00-00") ? 'Event End Date' : date("F j, Y", strtotime($value['ticket_end_sale_date']));?></td>
                  <td align="center"><?php if($value['ticket_price']==0){ echo " Free ";}else{ echo "$".$value['ticket_price'];}?></td>
                  <td align="right" nowrap="nowrap">                  
                  <?php if( $total_ticket_quantity > $value['ticket_sold']){ ?>                    
                    <select name="quant_<?=$value['id']?>" id="quant_<?=$value['id']?>" >
                      <?php if( ($total_ticket_quantity - $value['ticket_sold']) < 10 ) { ?>
                      <?php for($i=0;$i<=$total_ticket_quantity - $value['ticket_sold']; $i++){?>
                      <option value="<?php echo $i;?>"><?php echo $i;?></option>
                      <?php } ?>
                      <?php }else{?>               
                      
                      <option value="0">0</option>
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                      <option value="6">6</option>
                      <option value="7">7</option>
                      <option value="8">8</option>
                      <option value="9">9</option>
                      <option value="10">10</option>
                      <?php } ?>
                    </select>
                    <input type="hidden" name="can_order[]" id="can_order" value="1" />                    
                    <input type="hidden" name="tickets[]" id="tickets[]" value="<?=$value['id']?>" />
                    <input type="hidden" name="ticket_title['<?=$value['id']?>']" id="ticket_title_<?=$value['id']?>" value="<?=$value['ticket_title']?>" />
                    <input type="hidden" name="ticket_min_order['<?=$value['id']?>']" id="ticket_min_order_<?=$value['id']?>" value="<?=$value['ticket_min_order']?>" />
                    <input type="hidden" name="ticket_max_order['<?=$value['id']?>']" id="ticket_max_order_<?=$value['id']?>" value="<?=$value['ticket_max_order']?>" />
                  <?php } else {?>
                  Tickets Sold Out
                  <input type="hidden" name="can_order[]" id="can_order" value="0" />
                  <?php } ?>
                  </td>
                  <?php } else if(   time() <  strtotime($value['ticket_start_sale_date']) &&    time() < strtotime($value['ticket_end_sale_date']) ) {?>
                  <td align="center"><font color="red"><?=($value['ticket_start_sale_date']=="0000-00-00 00:00:00" || $value['ticket_start_sale_date']=="0000-00-00") ? 'Event Publish Date' : date("F j, Y", strtotime($value['ticket_start_sale_date']));?></font></td>
                  <td align="center"><font color="red"><?=($value['ticket_end_sale_date']=="0000-00-00 00:00:00" || $value['ticket_end_sale_date']=="0000-00-00") ? 'Event End Date' : date("F j, Y", strtotime($value['ticket_end_sale_date']));?></font></td>
                  <td align="center"><?php if($value['ticket_price']==0){ echo " Free ";}else{ echo "$".$value['ticket_price'];}?></td>
                  <td align="right" nowrap="nowrap"> Not yet started <input type="hidden" name="can_order[]" id="can_order" value="0" /></td>
                  <?php } else if(   time() >  strtotime($value['ticket_start_sale_date']) &&    time() > strtotime($value['ticket_end_sale_date']) ) {?>
                  <td align="center"><font color="red"><?=date("F j, Y", strtotime($value['ticket_start_sale_date']));?></font></td>
                  <td align="center"><font color="red"><?=date("F j, Y", strtotime($value['ticket_end_sale_date']));?></font></td>
                  <td align="center"><?php if($value['ticket_price']==0){ echo " Free ";}else{ echo "$".$value['ticket_price'];}?></td>
                  <td align="right" nowrap="nowrap"> Ticket sales ended <input type="hidden" name="can_order[]" id="can_order" value="0" /></td>
                  <? } ?>
                </tr>
                <? } else { ?>
                <tr class="ticket_row">
                  <td><strong><?=$value['ticket_title']?></strong></td>
                  <td align="center"><font color="red">Event Publish Date</font></td>
                  <td align="center"><font color="red">Event End Date</font></td>
                  <td align="center">$102</td>
                  <td nowrap="nowrap" align="right"><?php echo ($value['ticket_quantity']=="0")  ? 'infinite' : $value['ticket_quantity'];?></td>
                </tr>
                <? } ?>
                <?php } ?>
              </table>
              <table width="568" border="0">
                <tr>
                  <td width="424" align="right" valign="top"></td>
                  <td width="134" valign="bottom"><input type="hidden" name="eid" value="<?php echo $this->eventdetail['id'] ; ?>" /> <input type="submit" name="submit" class="buttoncontact" id="buttonsend" value="Order Now" /></td>
                </tr>
              </table>
              <? } ?>
            </div>
            </fieldset>
          </form>
      </div>
    </div>
    <div style="float:left; width:300px; margin-left:20px;">      
      <?php if($this->eventdetail['start_date']!="0000-00-00" || $this->eventdetail['start_date']!="0000-00-00"){ ?>
      <div class="event-rightcolum">
        <div class="label-form-inline">
          <label>
          <h4>When</h4>
          </label>
          <div><?php echo date("l, F j, Y", strtotime($this->eventdetail['start_date'])) ; ?> at <?php echo date("h:i A", strtotime($this->eventdetail['start_time'])) ; ?> <br />
            <span class="pipe">- to -</span><br />
            <?php echo date("l, F j, Y", strtotime($this->eventdetail['end_date'])) ; ?> at <?php echo date("h:i A", strtotime($this->eventdetail['end_time'])) ; ?> <?php echo $this->eventdetail['time_zone'] ; ?><br />
          </div>
        </div>
      </div>
      <?php } ?>
      <?php if( !empty($this->eventdetail['venue']) || !empty($this->eventdetail['city']) || !empty($this->eventdetail['state']) || !empty($this->eventdetail['country']) || !empty($this->eventdetail['zip']) ) { ?>
      <div class="event-rightcolum">
        <div class="label-form-inline">
          <label>
          <h4>Where</h4>
          </label>
          <div>             
            <?php echo (empty($this->eventdetail['venue'])) ? '' : $this->eventdetail['venue']."<br />"; ?>  
            <?php echo (empty($this->eventdetail['city'])) ? '' : $this->eventdetail['city'].", "; ?>
            <?php echo (empty($this->eventdetail['state'])) ? '' : $this->eventdetail['state'].", "; ?>
            <?php echo (empty($this->eventdetail['zip'])) ? '' : $this->eventdetail['zip']."<br /> "; ?>
            <?php echo (empty($this->eventdetail['country'])) ? '' : $this->eventdetail['country']." "; ?>                         
            <br />
          </div>
        </div>
      </div>
      <? } ?>      
    </div>
    <div style="clear: both;"></div>
    <div class="event-descaption-area">
        <div>          
            <fieldset>            
            <div id="scrollbar1">
    		<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
    		<div class="viewport">
    			 <div class="overview">
    				<?php echo $this->eventdetail['description']; ?>                   
    			</div>
    		</div>
    	    </div>
            </fieldset>          
          <!-- Contact Form End //-->
        </div>
     </div>
     <?php if( !empty($this->orgdetail['organization_name']) || !empty($this->orgdetail['organization_description']) ) { ?>
     <div style="clear: both;"></div>
      <div class="event-descaption-area">
        <div class="label-form-inline">
          <label>
          <h4>Host</h4>
          </label>
          <div><?php echo $this->orgdetail['organization_name']; ?></div>
          <div><?php echo $this->orgdetail['organization_description']; ?></div>
        </div>
      </div>
      <? } ?>
       
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){ 
    
    var can_submit = $('select[name*="quant_"]').val();
    if (typeof can_submit === "undefined") 
    {
        $('#buttonsend').hide(); $('.buttoncontact').hide();
    }
    
});
</script>