<div id="content">
	<div class="maincontent">    
    <div class="myeventbg">
    <div class="animatedtabs">
      <ul>
        <li><a href="/createevent" title="Create Event"><span>Create Event</span></a></li>
        <li><a href="/myevents"    title="My Events"><span>My Events</span></a></li>
        <li><a href="/mytickets"   title="My Purchased Tickets"><span>My Purchased Tickets</span></a></li>
        <li><a href="/deletedevents"   title="My Deleted Events"><span>My Deleted Events</span></a></li>
        <li><a href="/myprofile"   title="My Profile"><span>My Profile</span></a></li>
        <li><a href="/account"     title="My Account"><span>My Account</span></a></li>
        <li style="margin-left: 110px;"><a href="javascript:history.go(-1);" title="Go Back" ><span>Go Back</span></a></li>
      </ul>
    </div>   
    </div>
    <?php if(!empty($this->result)){?>
    <div id="eventLongBar">
      <div id="eventName">Event name</div>
      <div id="eventDate">Date</div>
      <div id="eventStatus">Status</div>  
      <div id="eventActions">Actions</div>
      <div style="clear: both;"></div>
      <?php 
      foreach($this->result as $key=>$value)
      {
      ?>
      <div onMouseOut="HideMyEventHoverBar(<?php echo $value['id']; ?>)" onMouseOver="ShowMyEventHoverBar(<?php echo $value['id']; ?>)" id="myevent<?php echo $value['id']; ?>" class="eventbar">
        <div class="eventUnderName"><?php echo $value['title']; ?></div>
        <div class="eventUnderDate"><?php echo $value['start_date']; ?></div>
        <div class="eventUnderStatus">Deleted</div>    
        <div style="display: none;" id="action<?php echo $value['id']; ?>" class="eventUnderActions">
          <div>
            <div id="recover">
              <p><a title="Event Recover" alt="Event Recover" href="/deleteevent?eid=<?php echo $value['id']; ?>" data="11" id="recover_delete_events" class="press-it-btn"></a></p>
            </div>
          </div>
        </div>
      </div>
      <div style="clear: both;"></div>
      <?php } ?>
    </div>
    <?php }else{?>
    <div style="text-align: center;">There are no records</div>
    <?php } ?>
    
    
        
    
	</div>
</div>