<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title><?php echo $this->escape($this->title); ?></title>
    
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/js/ExtJs/resources/css/ext-all.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/js/ExtJs/plugins/shared/example.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/stylesheets/icons.css" />   
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/stylesheets/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/stylesheets/superfish.css" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/js/ExtJs/plugins/superboxselect/boxselect.css" />

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/ExtJs/ext-all.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/ExtJs/plugins/superboxselect/boxselect.js"></script>     

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/hoverIntent.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/superfish.js"></script>
<script type="text/javascript">

// initialise plugins
jQuery(function(){
	jQuery('ul.sf-menu').superfish();
});


</script>
<script type="text/javascript" src="/assets/js/ExtJs/ext-core-debug.js"></script>
<script type="text/javascript">
  Ext.Loader.setConfig({
      enabled: true
  });
</script>


</head>

<body>
<?php echo $this->layout()->header; ?>
<?php echo $this->layout()->menu; ?>
<div id="content_wrapper">
<?php echo $this->layout()->content; ?>
</div>
</body>
</html>