<!-- BEGIN OF FOOTER -->
<div id="bottom-wrapper">        
    <div id="bottom-content">
        <div class="logofooter-column">
            <img src="/static/images/logo.png" alt="" />
        </div>
        <div class="contactbottom-column">
            <h6>Contact Us</h6>
            <p>Tel: +44 0208 1234 355 <br/>
            Fax: +44 0208 1234 344 <br/>
            Email: eventcommander@wiztechpk.com <br/>
            Skype: eventcommander                                 
            </p>
        </div>
        <div class="socialbottom-column">
            <h6>Follow Us</h6>
            <ul class="social-list">
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social6.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social5.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social2.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social12.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social4.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social20.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social11.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social26.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social7.png" alt="" /></a></li>
                <li><a href="#"><img src="/static/images/social-icons/follow-footer/social18.png" alt="" /></a></li>
            </ul>
        </div>
        <div class="linkbottom-column">
            <h6>Media Center</h6>
            <ul class="list-bottom">
                <li><a href="#">Media Release</a></li>
                <li><a href="#">In The Media</a></li>
                <li><a href="#">FAQ</a></li>
            </ul>
        </div>
        <div class="mailingbottom-column">
            <h6>Mailing List</h6>
            <p>Sign up if you would like to receive occasional treats from us.</p>
            <form id="newsletter" action="#" method="get">
                <fieldset class="search-fieldset">
                <input type="text" id="nlt-form" value="Your email address..." onblur="if (this.value == ''){this.value = 'Your email address...'; }" onfocus="if (this.value == 'Your email address...') {this.value = ''; }" />
                <input type="submit" class="sub-button" value="Go" />                            
                </fieldset>      						
                </form>
        </div>         	
    </div>
</div>            

<div id="copyright-text">
  	Copyright &copy; 2011 <?php echo $this->layout()->websitetitle;?>. All rights reserved &nbsp;
</div>
<!-- END OF FOORTER -->