<!-- BEGIN OF HEADER -->
<div id="header-container">
  <div id="phone-number">
    <h3>777.888.5555</h3>
  </div>
  <div id="slideshow-wrapper">
    <div id="s3slide">
      <ul id="s3slideContent">
        <li class="s3slideImage"> <img style="background: url('/static/images/accordion2.jpg') no-repeat 0 0" src="/static/images/space.gif" width="960" height="377" alt="" />          
        </li>
        <li class="s3slideImage"> <img style="background: url('/static/images/accordion1.jpg') no-repeat 0 0" src="/static/images/space.gif" width="960" height="377" alt="" />          
        </li>
        <li class="s3slideImage"> <img style="background: url('/static/images/accordion3.jpg') no-repeat 0 0" src="/static/images/space.gif" width="960" height="377" alt="" />          
        </li>
        <li class="s3slideImage"> <img style="background: url('/static/images/accordion4.jpg') no-repeat 0 0" src="/static/images/space.gif" width="960" height="377" alt="" />          
        </li>
        <div class="clear s3slideImage"></div>
      </ul>
    </div>
  </div>
  <div id="slideshow-shadow"></div>
</div>
<!-- END OF HEADER -->
