<div id="content">
	<div class="maincontent">   
    <div class="myeventbg">
    <div class="animatedtabs">
      <ul>
        <li><a href="/createevent" title="Create Event"><span>Create Event</span></a></li>
        <li><a href="/myevents"    title="My Events"><span>My Events</span></a></li>
        <li><a href="/mytickets"   title="My Purchased Tickets"><span>My Purchased Tickets</span></a></li>
        <li><a href="/deletedevents"   title="My Deleted Events"><span>My Deleted Events</span></a></li>
        <li><a href="/myprofile"   title="My Profile"><span>My Profile</span></a></li>
        <li><a href="/account"     title="My Account"><span>My Account</span></a></li>
        <li style="margin-left: 110px;"><a href="javascript:history.go(-1);" title="Go Back" ><span>Go Back</span></a></li>
      </ul>
    </div>   
    </div>
    <?php if(trim($_REQUEST['filter'])== 'live'){ $filter = 'Published'; } else { $filter = 'Draft'; } ?>   
    
    <?php echo $this->MyEvents($filter); ?>
    								 
	           

	
    </div>
</div>