<div id="content">
  <div class="maincontent-inner">
    <div class="col-1">
      <h3>We'd love to hear your feedback</h3>
      <p>Send us you comment and queries</p>
    </div>
    <div class="col-2">
      <!-- begin of contact form -->
      <div class="contact-area">
        <h4>Contact From</h4>
        <div id="contactFormArea">
          <!-- Contact Form Start //-->
          <form action="#" id="contactform">
            <fieldset>
            <div class="label-form-inline">
              <label>Name</label>
              <input type="text" name="name" class="textfield" id="name" value="" />
            </div>
            <div class="label-form-inline">
              <label>Email</label>
              <input type="text" name="email" class="textfield" id="email" value="" />
            </div>
            <div class="label-form-inline">
              <label>Subject</label>
              <input type="text" name="subject" class="textfield field-nomargin" id="subject" value="" />
            </div>
            <label>Message</label>
            <textarea name="message" id="message" class="textarea" cols="2" rows="7"></textarea>
            <input type="submit" name="submit" class="buttoncontact" id="buttonsend" value="Submit" />
            <span class="loading" style="display: none;">Please wait..</span>
            </fieldset>
          </form>
          <!-- Contact Form End //-->
        </div>
      </div>
      <!-- begin of contact form -->
    </div>    
    
  </div>
</div>