<div id="content">
	<div class="maincontent">
    <div class="myeventbg">
    <div class="animatedtabs">
      <ul>
        <li><a href="/createevent" title="Create Event"><span>Create Event</span></a></li>
        <li><a href="/myevents"    title="My Events"><span>My Events</span></a></li>
        <li><a href="/mytickets"   title="My Purchased Tickets"><span>My Purchased Tickets</span></a></li>
        <li><a href="/deletedevents"   title="My Deleted Events"><span>My Deleted Events</span></a></li>
        <li><a href="/myprofile"   title="My Profile"><span>My Profile</span></a></li>
        <li><a href="/account"     title="My Account"><span>My Account</span></a></li>
        <li style="margin-left: 110px;"><a href="javascript:history.go(-1);" title="Go Back" ><span>Go Back</span></a></li>
      </ul>
    </div>   
    </div>
    <link href="/static/css/account.css" rel="stylesheet" type="text/css" /> 
    <div id="col_210">
		<div id="sidenav">
        	<ul>
        		<li class="text">Your Account</li>
                <li class="tab"><a href="/account">Contact Info</a></li>
                <li class="tab"><a href="/password">Password</a></li>
                <li class="tab"><a href="/invoices">Invoices</a></li>
                    <li class="tab"><a href="/transactions">Transactions</a></li>
                    <li class="tab_live"><a href="/receipts">Receipts</a></li>
                    <li class="tab"><a href="/membershipstatus">Membership status</a></li>
                
                <li class="tab"><a href="/account-close">Close Account</a></li>        
        	</ul>
        </div><!-- end sidenav -->
	</div>
    <div style="float: left; min-height: 400px; height: auto; "><img src="/static/images/space.gif" /></div>
    <div class="animatedtabs" style="overflow: visible;">
      <ul>
        <li><a href="/transactions" title="Transactions"><span>Transactions</span></a></li>
        <li class="selected"><a href="/receipts"    title="Receipts"><span>Receipts</span></a></li>
        <li><a href="/membershipstatus"   title="Membership Status"><span>Membership Status</span></a></li>        
      </ul>
    </div>   
    <div style="float: left; height: 20px; width: 700px; padding-top: 5px; padding-bottom: 5px; "><h5>Receipts</h5></div>
        
    <?php
    $rowstyle               =   "class= 'horizontalbar1'";
    $dbAdapter              =   Zend_Db_Table::getDefaultAdapter();
    $sql                    =   "SELECT e.id, e.title, e.start_date, o.id AS oid, o.total_quantity, o.total_amount, DATE_FORMAT(o.date_created, '%m/%d/%Y') AS order_date FROM `events` e INNER JOIN `orders` o ON e.id=o.eid WHERE o.mid = '".Zend_Auth::getInstance()->getIdentity()->id."' ORDER BY e.id DESC LIMIT 5";
    $resultreceipts                 =   $dbAdapter->fetchAll($sql);   
    if(!empty($resultreceipts)){                             
    ?>  
    <div id="invoiceListing">
    <div id="eventName">Event Title</div>        
    <div id="eventDate">Total Quantity</div>
    <div id="eventStatus">Total Amount</div>
    <div id="eventDate">Order Date</div>
    <div id="eventActions">Actions</div>
    <div style="clear:both;"></div>
    <div style="height: 2px; border-bottom: #DADADA solid ;  ">&nbsp;</div>
    <?     
    foreach($resultreceipts as $value) {                            
    ?>    
    <div <?php echo $rowstyle;?> >
    <div class="eventUnderName"><?php echo $value['title']; ?></div>         
    <div class="eventUnderDate"><?php echo $value['total_quantity']; ?></div> 
    <div class="eventUnderStatus"><?php if($value['total_amount']==0){ echo " Free ";}else{ echo "$".$value['total_amount'];}?></div>
    <div class="eventUnderDate"><?php echo $value['order_date']; ?></div>       
    <div class="eventUnderActions"><img src="/static/images/preview.png" width="24" height="24" class="prview_ordertransaction" data="<?php echo $value['oid']; ?>" style="cursor: pointer;" /></div> 
    </div>
    <div style="clear:both;"></div> 
    <? 
    $rowstyle == "class= 'horizontalbar1'" ? $rowstyle = "class= 'horizontalbar2'" : $rowstyle = "class= 'horizontalbar1'";
    }       
    ?>
    <div style="float: right; text-align: right; height: 15px; width: 700px; padding-top: 5px; padding-bottom: 5px;"><a href="/transactions/ticketorder"> View All </a></div>
    <div style="height: 5px;"><hr /></div>    
    <?php } else {?>
    <div style="float: left; height: 20px; width: 700px; text-align: center;">There are no records</div>
    <div style="height: 5px;"><hr /></div>
    <?php } ?>
    </div>    
       
</div>  
	




	<!-- end content -->
	

